// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7d2qi6bDVs6XuDxMTdahRmOJwC1wdtU',
    appId: '1:170237155930:web:6c18718ec3ff2df2e71663',
    messagingSenderId: '170237155930',
    projectId: 'neon-notes-application',
    authDomain: 'neon-notes-application.firebaseapp.com',
    storageBucket: 'neon-notes-application.firebasestorage.app',
    measurementId: 'G-KVC80XY6DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8izpULWG4qAEPunVnOQMgMePOcFa6bXE',
    appId: '1:170237155930:android:6da3d05198ac2da1e71663',
    messagingSenderId: '170237155930',
    projectId: 'neon-notes-application',
    storageBucket: 'neon-notes-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAew-__ovB3ienrzKi1kc2bf3E1hiMQqrQ',
    appId: '1:170237155930:ios:98b6d4b426094b2be71663',
    messagingSenderId: '170237155930',
    projectId: 'neon-notes-application',
    storageBucket: 'neon-notes-application.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAew-__ovB3ienrzKi1kc2bf3E1hiMQqrQ',
    appId: '1:170237155930:ios:98b6d4b426094b2be71663',
    messagingSenderId: '170237155930',
    projectId: 'neon-notes-application',
    storageBucket: 'neon-notes-application.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu7d2qi6bDVs6XuDxMTdahRmOJwC1wdtU',
    appId: '1:170237155930:web:ace3ea76373ecb1fe71663',
    messagingSenderId: '170237155930',
    projectId: 'neon-notes-application',
    authDomain: 'neon-notes-application.firebaseapp.com',
    storageBucket: 'neon-notes-application.firebasestorage.app',
    measurementId: 'G-DNPLLWECN9',
  );
}
